<a href="https://colab.research.google.com/github/sanjay-29218/tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this chapter we're going to covers some of the most fundamental concepts of tensors using tensorflow

* Introduction to tensorflow
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function(a way to speed up your regular Python function)
* Using GPUs with Tensorflow (for tpus)
* Exercises to try for yourself


Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
#Create tensors with tf.constant()
scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:

# Check the dimension of our vector
vector.ndim


1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[19,7],[1,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19,  7],
       [ 1,  3]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[19,5],[2,5],[6,7]],dtype=tf.float16) # specify the data type with dtype parameter

In [ ]:
# Lets create a tensor
tensor = tf.constant([])

Creating tf variable

In [ ]:
changebleTensor = tf.Variable([1,3])
unchangebleTensor = tf.constant([1,3])
changebleTensor[0],unchangebleTensor[0]

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
changebleTensor[0].assign(7)
changebleTensor[0],unchangebleTensor[0]

(<tf.Tensor: shape=(), dtype=int32, numpy=7>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
# Create  a random Tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2 ))
random_2 = tf.random.Generator.from_seed(43)
random_2 = random_2.normal(shape=(3,2))
random_1 , random_2 , random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

> Make global and operational seed same to get same result as unshuffled

In [ ]:
tf.random.set_seed(42)
unshuffledTensor = tf.random.Generator.from_seed(3)
unshuffledTensor = unshuffledTensor.normal(shape=(3,2))
shuffledTensor = tf.random.shuffle(unshuffledTensor,seed=42)
unshuffledTensor,shuffledTensor

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.43640924, -1.9633987 ],
        [-0.06452483, -1.056841  ],
        [ 1.0019137 ,  0.6735137 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.43640924, -1.9633987 ],
        [-0.06452483, -1.056841  ],
        [ 1.0019137 ,  0.6735137 ]], dtype=float32)>)

Other ways to make tensor

In [ ]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,4 ))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# Getting information from tensor
#Rank
#Axis
#Size

In [ ]:
zeros = tf.zeros(shape=(2,3,4))
zeros.shape,zeros.ndim,tf.size(zeros).numpy(),zeros.dtype,zeros.shape[0],zeros.shape[-1]

(TensorShape([2, 3, 4]), 3, 24, tf.float32, 2, 4)