<a href="https://colab.research.google.com/github/sanjay-29218/tensorflow/blob/main/01tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Second day 


In [ ]:
import tensorflow as tf

In [ ]:
rank_4_tensor=tf.zeros(shape=(2,3,4,5))

In [ ]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:3,:2,:1]

<tf.Tensor: shape=(1, 3, 2, 1), dtype=float32, numpy=
array([[[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2dimension)

In [ ]:
rank_2_tensor=tf.constant([
    [2,3],
    [4,5]
])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [ ]:
#Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor
# ... means every axis before that

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis =0) #expand the 0axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [4, 5]]], dtype=int32)>

##Manipulating tensors(tensor Operation)
*Addition*
*Multiplication*
*Division*


In [ ]:
#Addition
simple_tensor = tf.constant([[3,4],
                 [5,5]])
simple_tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 14],
       [15, 15]], dtype=int32)>

In [ ]:
simple_tensor - 20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-17, -16],
       [-15, -15]], dtype=int32)>

In [ ]:
simple_tensor*2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 10]], dtype=int32)>

In [ ]:
# Alternative for above operation
tf.multiply(simple_tensor , 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 10]], dtype=int32)>

In [ ]:
tf.add(simple_tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 14],
       [15, 15]], dtype=int32)>

## Matrix multiplication


In [ ]:
# matrix multiplication in tensor flow

In [ ]:
tf.matmul(simple_tensor,simple_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[29, 32],
       [40, 45]], dtype=int32)>

In [ ]:
X= tf.constant([[1,2,5],
                      [7,2,1],
                      [3,3,3]])
Y = tf.constant([[3,5,1],
                       [6,7,1]
                       ])
Z = tf.matmul(X,Y)
Z

InvalidArgumentError: ignored

In [ ]:
X@tf.reshape(Y,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[40, 22],
       [30, 48],
       [33, 36]], dtype=int32)>

In [ ]:
a = tf.random.Generator.from_seed(42).normal(shape=(3,2))
b = tf.random.Generator.from_seed(43).normal(shape=(2,3))
a@b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.21043749,  1.4216603 , -0.03638695],
       [ 0.62363327,  0.8100108 ,  0.7263864 ],
       [ 0.97727114,  1.784562  ,  1.0119911 ]], dtype=float32)>

# Lets try transpose

In [ ]:
a,b,tf.transpose(a),tf.transpose(b)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ,  0.09988727],
        [-0.50998646, -0.7535805 , -0.57166284]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.7565803 ,  0.07595026, -0.23193763],
        [-0.06854702, -1.2573844 , -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193763, -0.50998646],
        [-1.8107855 , -0.7535805 ],
        [ 0.09988727, -0.57166284]], dtype=float32)>)

In [ ]:
tf.transpose(a)@tf.transpose(b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.0147822, 0.4612012],
       [2.111878 , 2.0176573]], dtype=float32)>

from numpy import product
** THe DOT PRODUCT **
Matrix multiplication is also referred to as the dot product

You can perform matrix multiplication using:
'tf.matmul()'
'tf.tensordot()'

In [ ]:
#Perform  the dot product on X and Y (requires X or Y to be transposed)s
tf.tensordot(tf.transpose(a),tf.transpose(b),axes=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.0147822, 0.4612012],
       [2.111878 , 2.0176573]], dtype=float32)>

#CHanging the datatype of a tensor

In [ ]:
# Create a new tensor with default datatype (float 32) 


In [ ]:
B = tf.constant([[1,2],[3,4]])

B,B.dtype

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 tf.int32,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[5, 6],
        [7, 8]], dtype=int32)>,
 tf.int32)

In [ ]:
D = tf.constant([[5,6],[7,8]])
D,D.dtype

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[5, 6],
        [7, 8]], dtype=int32)>, tf.int32)

In [ ]:
C = tf.cast(D,dtype=tf.float16)
C,C.dtype

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[5., 6.],
        [7., 8.]], dtype=float16)>, tf.float16)

In [ ]:
E = tf.cast(B , dtype=tf.float16)
E,E.dtype

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float16)>, tf.float16)

###Aggregating tensors

In [ ]:
#Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
#Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

#Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Create a random tensor with values between 1 to 50
import numpy as np
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([78, 26, 28, 24, 99, 11, 43, 42, 24, 12, 56, 25, 37, 81, 95, 51, 64,
       19, 48, 12, 49, 92, 25, 90, 90, 48, 33, 32, 79, 68, 33, 87, 33, 22,
       84, 35, 58, 63, 91, 26, 84, 58, 57, 77, 86, 94, 63, 75, 84, 81])>

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=11>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=55>

In [ ]:
import tensor_probability as tfp

ModuleNotFoundError: ignored

In [ ]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.732872>

In [ ]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=714.6464>

Find the positional maximum and minimum

In [ ]:
#Create a new tensor for finding positional maximum and minimum
# tf.random.Generator.from_seed(42)
tf.random.set_seed(42) # set the seed to 42 constant
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
assert F[tf.argmax(F)] == tf.reduce_max(F) # assert give error if it is

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

##Squeezing the tensor(removing all single dimension)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
g = tf.random.uniform(shape=[50])

In [ ]:
g_squeezed = tf.squeeze(g)
g_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-hot encoding

In [ ]:
# Create a list of indices
some_list = [0,1,2,3,4] # could be red , greeen, blue, purple
# One hot encode our list of indices
tf.one_hot(some_list , depth=4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# Find the log 

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

###Tensors and Numpy

In [ ]:
 #Create a tensor directly from a Numpy array
J = tf.constant(np.array([1.,2.,3.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [ ]:
# Convert our tensor back to numpy array
np.array(J) , type(np.array(J))

(array([1., 2., 3.]), numpy.ndarray)

In [ ]:
# Convert the tensor J to a Numpy array
J.numpy() , type(J.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,5.,3.]))
tensor_J = tf.constant([1,2,3])
numpy_J , tensor_J


(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 5., 3.])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>)